/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as BirthdaysRouteImport } from './routes/birthdays'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FoodRouteImport } from './routes/food'
import { Route as MedicationsRouteImport } from './routes/medications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as WalkRouteImport } from './routes/walk'
import { Route as WorkoutProgramsRouteImport } from './routes/workout-programs'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as ApiAssistantRouteImport } from './routes/api/assistant'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthdaysRoute = BirthdaysRouteImport.update({
  id: '/birthdays',
  path: '/birthdays',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsRoute = MedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkRoute = WalkRouteImport.update({
  id: '/walk',
  path: '/walk',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutProgramsRoute = WorkoutProgramsRouteImport.update({
  id: '/workout-programs',
  path: '/workout-programs',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/bills': typeof BillsRoute
  '/birthdays': typeof BirthdaysRoute
  '/documents': typeof DocumentsRoute
  '/food': typeof FoodRoute
  '/medications': typeof MedicationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasks': typeof TasksRoute
  '/walk': typeof WalkRoute
  '/workout-programs': typeof WorkoutProgramsRoute
  '/workouts': typeof WorkoutsRoute
  '/api/assistant': typeof ApiAssistantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/bills': typeof BillsRoute
  '/birthdays': typeof BirthdaysRoute
  '/documents': typeof DocumentsRoute
  '/food': typeof FoodRoute
  '/medications': typeof MedicationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasks': typeof TasksRoute
  '/walk': typeof WalkRoute
  '/workout-programs': typeof WorkoutProgramsRoute
  '/workouts': typeof WorkoutsRoute
  '/api/assistant': typeof ApiAssistantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/bills': typeof BillsRoute
  '/birthdays': typeof BirthdaysRoute
  '/documents': typeof DocumentsRoute
  '/food': typeof FoodRoute
  '/medications': typeof MedicationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasks': typeof TasksRoute
  '/walk': typeof WalkRoute
  '/workout-programs': typeof WorkoutProgramsRoute
  '/workouts': typeof WorkoutsRoute
  '/api/assistant': typeof ApiAssistantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/analytics'
    | '/appointments'
    | '/auth'
    | '/bills'
    | '/birthdays'
    | '/documents'
    | '/food'
    | '/medications'
    | '/onboarding'
    | '/profile'
    | '/services'
    | '/sitemap.xml'
    | '/tasks'
    | '/walk'
    | '/workout-programs'
    | '/workouts'
    | '/api/assistant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/analytics'
    | '/appointments'
    | '/auth'
    | '/bills'
    | '/birthdays'
    | '/documents'
    | '/food'
    | '/medications'
    | '/onboarding'
    | '/profile'
    | '/services'
    | '/sitemap.xml'
    | '/tasks'
    | '/walk'
    | '/workout-programs'
    | '/workouts'
    | '/api/assistant'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/analytics'
    | '/appointments'
    | '/auth'
    | '/bills'
    | '/birthdays'
    | '/documents'
    | '/food'
    | '/medications'
    | '/onboarding'
    | '/profile'
    | '/services'
    | '/sitemap.xml'
    | '/tasks'
    | '/walk'
    | '/workout-programs'
    | '/workouts'
    | '/api/assistant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AuthRoute: typeof AuthRoute
  BillsRoute: typeof BillsRoute
  BirthdaysRoute: typeof BirthdaysRoute
  DocumentsRoute: typeof DocumentsRoute
  FoodRoute: typeof FoodRoute
  MedicationsRoute: typeof MedicationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TasksRoute: typeof TasksRoute
  WalkRoute: typeof WalkRoute
  WorkoutProgramsRoute: typeof WorkoutProgramsRoute
  WorkoutsRoute: typeof WorkoutsRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birthdays': {
      id: '/birthdays'
      path: '/birthdays'
      fullPath: '/birthdays'
      preLoaderRoute: typeof BirthdaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications': {
      id: '/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof MedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walk': {
      id: '/walk'
      path: '/walk'
      fullPath: '/walk'
      preLoaderRoute: typeof WalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout-programs': {
      id: '/workout-programs'
      path: '/workout-programs'
      fullPath: '/workout-programs'
      preLoaderRoute: typeof WorkoutProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AnalyticsRoute: AnalyticsRoute,
  AppointmentsRoute: AppointmentsRoute,
  AuthRoute: AuthRoute,
  BillsRoute: BillsRoute,
  BirthdaysRoute: BirthdaysRoute,
  DocumentsRoute: DocumentsRoute,
  FoodRoute: FoodRoute,
  MedicationsRoute: MedicationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TasksRoute: TasksRoute,
  WalkRoute: WalkRoute,
  WorkoutProgramsRoute: WorkoutProgramsRoute,
  WorkoutsRoute: WorkoutsRoute,
  ApiAssistantRoute: ApiAssistantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
